export * from "./admission";
export * from "./course";
export * from "./section";
export * from "./assignment";
export * from "./registration";
export * from "./attendance";
export * from "./assessment";
export * from "./freeze";
export * from "./hall-ticket";
