export const admissionModes = [
  "KCET",
  "COMED-K",
  "MANAGEMENT",
  "PIO/Foreign/Gulf",
  "PMSSS",
  // "DCET",
  // "PGCET",
  // "GOI",
] as const;

const ugPgCategories = [
  "1G",
  "1K",
  "1R",
  "1H",
  "1KH",
  "1RH",
  "2AG",
  "2AK",
  "2AR",
  "2AH",
  "2AKH",
  "2ARH",
  "2BG",
  "2BH",
  "2BKH",
  "2BRH",
  "2BK",
  "2BR",
  "3AG",
  "3AK",
  "3AR",
  "3AH",
  "3AKH",
  "3ARH",
  "3BG",
  "3BK",
  "3BR",
  "3BH",
  "3BKH",
  "3BRH",
  "GM",
  "GMK",
  "GMR",
  "GMH",
  "GMKH",
  "GMRH",
  "SCG",
  "SCK",
  "SCR",
  "SCH",
  "SCKH",
  "SCRH",
  "STG",
  "STK",
  "STR",
  "STH",
  "STKH",
  "STRH",
  "PH",
  "NCC",
  "JK",
  "SPT",
  "SNO",
] as const;

const reservationCategories = [
  "SC",
  "ST",
  "CAT-1",
  "2A",
  "2B",
  "3A",
  "3B",
  "GM",
] as const;

export const categoriesClaimed = {
  KCET: ugPgCategories,
  DCET: ugPgCategories,
  PGCET: ugPgCategories,
  "COMED-K": ["GM", "HK"],
  MANAGEMENT: reservationCategories,
  "PIO/Foreign/Gulf": ["PIO", "Foreign", "Gulf"],
  PMSSS: reservationCategories,
  GOI: reservationCategories,
} as const;

export const categoriesAllotted = {
  KCET: ugPgCategories,
  DCET: ugPgCategories,
  PGCET: ugPgCategories,
  "COMED-K": ["GM", "HK"],
  MANAGEMENT: ["GM"],
  "PIO/Foreign/Gulf": ["PIO", "Foreign", "Gulf"],
  PMSSS: ["GM"],
  GOI: ["GM"],
} as const;
export const quotas = ["MERIT", "MANAGEMENT", "SPORTS", "NRI", "SNQ"] as const;
