export const admissionModes = [
  "KCET",
  "COMED-K",
  "MANAGEMENT",
  "PIO/Foreign/Gulf",
  "PMSSS",
  // "DCET",
  // "PGCET",
  // "GOI",
] as const;

export const categoriesClaimed = {
  KCET: [
    "GM",
    "GMR",
    "GMH",
    "GMKH",
    "GMRH",
    "1G",
    "1K",
    "1R",
    "1H",
    "1KH",
    "1RH",
    "2AG",
    "2AK",
    "2AR",
    "2AH",
    "2AKH",
    "2ARH",
    "2BG",
    "2BH",
    "2BRH",
    "2BK",
    "3AG",
    "3AK",
    "3AH",
    "3AKH",
    "3ARH",
    "3BG",
    "3BH",
    "3BK",
    "3BKH",
    "3BRH",
    "SCG",
    "SCK",
    "SCR",
    "SCH",
    "SCKH",
    "STG",
    "STK",
    "STR",
    "STH",
    "STKH",
    "STRH",
    "PH",
    "NCC",
    "JK",
    "SPT",
    "SNQ",
  ],

  "COMED-K": ["GM", "HK"],

  MANAGEMENT: ["GM", "SC", "ST", "CAT-1", "2A", "2B", "3A", "3B"],

  "PIO/Foreign/Gulf": ["PIO", "Foreign", "Gulf"],

  PMSSS: ["SC", "ST", "CAT-1", "2A", "2B", "3A", "3B", "GM"],
} as const;

export const categoriesAllotted = {
  ...categoriesClaimed,
} as const;
export const quotas = ["MERIT", "MANAGEMENT", "SPORTS", "NRI", "SNQ"] as const;
