export * from "./admission-user.schema";
export * from "./course-assignment.schema";
export * from "./course.schema";
export * from "./freeze.schema";
export * from "./registration-tracking.schema";
export * from "./registration-window.schema";
export * from "./semester.schema";
export * from "./student.schema";
export * from "./user.schema";
