import { z } from "zod";

// Define the Zod enum to match Prisma
export const DesignationEnum = z.enum([
  "ASSOCIATE_PROFESSOR",
  "ASSISTANT_PROFESSOR",
  "PROFESSOR",
  "VISITING_PROFESSOR",
]);

export const BaseFacultySchema = z.object({
  userId: z.string().uuid("Invalid user ID"),
  departmentId: z.string().uuid("Invalid department ID"), // Changed from departmentName
  shortName: z.string().min(1, "Short name is required"),
  designation: DesignationEnum,
});

// For creation, we OMIT userId and shortName because:
// 1. userId will be created during the auth.api.createUser step
// 2. shortName will be automatically generated by our backend logic
export const CreateFacultySchema = z.object({
  departmentId: z.string().uuid("Invalid department ID"),
  designation: DesignationEnum,
});

export const UpdateFacultySchema = BaseFacultySchema.partial();

export const FacultyResponseSchema = BaseFacultySchema.extend({
  id: z.string().uuid("Invalid faculty ID"),
});

export type BaseFacultyType = z.infer<typeof BaseFacultySchema>;
export type CreateFacultyType = z.infer<typeof CreateFacultySchema>;
export type UpdateFacultyType = z.infer<typeof UpdateFacultySchema>;
export type FacultyResponseType = z.infer<typeof FacultyResponseSchema>;
